version: "3"
services:
 cooperativePostgres:
  image: postgres:latest
  network_mode: bridge
  container_name: cooperative-postgres
  volumes:
   - postgres-data:/var/lib/postgresql/data
  expose:
   - 5432
  ports:
   - 5433:5432
  environment:
   - POSTGRES_PASSWORD=root
   - POSTGRES_USER=root
   - POSTGRES_DB=cooperative
  restart: unless-stopped
 cooperativeUsersApi:
  image: cooperative-users-api
  network_mode: bridge
  container_name: cooperative-users-api
  expose:
   - 5002
  ports:
   - 5002:5002
  restart: unless-stopped
  depends_on:
   - cooperativePostgres
  links:
   - cooperativePostgres
 cooperativeApi:
  image: cooperative-api
  network_mode: bridge
  container_name: cooperative-api
  expose:
   - 5001
  ports:
   - 5001:5001
  restart: unless-stopped
  depends_on:
   - cooperativePostgres
   - cooperativeUsersApi
  links:
   - cooperativePostgres
   - cooperativeUsersApi
 cooperativeMvpAPP:
  image: cooperative-app
  network_mode: bridge
  container_name: cooperative-app
  expose:
   - 3000
  ports:
   - 3001:3000
  restart: unless-stopped
  links:
   - cooperativeApi
volumes:
 postgres-data:
